import React, { useState } from 'react';
import { FileText, Download, Check, Sparkles } from 'lucide-react';
import { jsPDF } from 'jspdf';

export const MarkdownToPdf: React.FC = () => {
  const [title, setTitle] = useState('OmniTools_Startup_Spec');
  const [content, setContent] = useState(`OmniTools SaaS - 2026 Specification Document

1. Architecture Overview
Client-side zero-server execution ensures instant page loads, zero runtime crashes, and zero host bills on Vercel.

2. Failover Intelligence
The Gemini 4-cluster rotation dynamically intercepts rate limits and continues user generation uninterrupted.

3. Aesthetics
A modern balanced palette of rose pink, warm yellow, and clean white.`);
  const [downloading, setDownloading] = useState(false);

  function generatePDF() {
    setDownloading(true);
    try {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

      // Accent Top Bar
      doc.setFillColor(244, 63, 94);
      doc.rect(0, 0, 105, 5, 'F');
      doc.setFillColor(245, 158, 11);
      doc.rect(105, 0, 105, 5, 'F');

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      doc.text(title.replace(/_/g, ' ').toUpperCase(), 14, 20);

      // Subtitle
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by OmniTools SaaS Studio · ${new Date().toLocaleDateString()}`, 14, 26);
      doc.line(14, 30, 196, 30);

      // Body
      doc.setFontSize(10.5);
      doc.setTextColor(51, 65, 85);
      const lines = doc.splitTextToSize(content, 182);
      let y = 38;

      for (let i = 0; i < lines.length; i++) {
        if (y > 275) {
          doc.addPage();
          y = 20;
        }
        doc.text(lines[i], 14, y);
        y += 6;
      }

      // Safe Mobile Download via Blob URL
      const blob = doc.output('blob');
      const blobUrl = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = blobUrl;
      a.download = `${title.toLowerCase().replace(/[^a-z0-9]/g, '_')}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(blobUrl);
    } catch (e) {
      alert("Error compiling PDF: " + e);
    } finally {
      setTimeout(() => setDownloading(false), 1200);
    }
  }

  return (
    <div className="max-w-3xl mx-auto space-y-4">
      <div className="bg-white border border-slate-200/90 rounded-3xl p-5 sm:p-6 space-y-4 shadow-sm">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-10 h-10 rounded-2xl bg-amber-50 border border-amber-200 text-amber-600 flex items-center justify-center font-bold">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-base text-slate-900">Markdown to PDF Studio</h3>
              <p className="text-xs text-slate-500">Instant client-side document compiler</p>
            </div>
          </div>
          <button
            onClick={generatePDF}
            disabled={downloading}
            className="bg-amber-400 hover:bg-amber-500 text-slate-950 text-xs font-bold px-4 py-2.5 rounded-xl flex items-center gap-1.5 shadow-sm transition active:scale-95"
          >
            {downloading ? <Check className="w-4 h-4 text-emerald-800" /> : <Download className="w-4 h-4" />}
            <span>{downloading ? 'Generated!' : 'Download PDF'}</span>
          </button>
        </div>

        <div>
          <label className="text-xs font-bold text-slate-700 block mb-1">Document Title</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3.5 py-2.5 text-xs font-semibold text-slate-900 focus:outline-none"
          />
        </div>

        <div>
          <label className="text-xs font-bold text-slate-700 block mb-1">Content Body</label>
          <textarea
            rows={10}
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="w-full bg-slate-50 border border-slate-200 rounded-xl p-3.5 text-xs font-mono text-slate-800 focus:outline-none leading-relaxed"
          />
        </div>
      </div>
    </div>
  );
};
